# STOP! This file was generated by an automated process.
# Any edits you make will be lost the next time it is
# re-generated.
view: Contact {
  sql_table_name: `Person.Contact` ;;

  dimension: Name {
    sql: CONCAT(${TABLE}.FirstName,' ',${TABLE}.LastName) ;;
  }

  dimension: ContactID {
    sql: ${TABLE}.ContactID ;;
  }
}
