# STOP! This file was generated by an automated process.
# Any edits you make will be lost the next time it is
# re-generated.
view: ProductCategory {
  sql_table_name: `Production.ProductCategory` ;;

  dimension: ProductCategoryName {
    sql: ${TABLE}.Name ;;
  }

  dimension: ProductCategoryID {
    sql: ${TABLE}.ProductCategoryID ;;
  }
}
