# STOP! This file was generated by an automated process.
# Any edits you make will be lost the next time it is
# re-generated.
view: WorkOrder {
  sql_table_name: `Production.WorkOrder` ;;

  dimension: ProductID {
    sql: ${TABLE}.ProductID ;;
  }

  measure: ScrappedQty {
    type: sum
    sql: ${TABLE}.ScrappedQty ;;
  }

  measure: StockedQty {
    type: sum
    sql: ${TABLE}.StockedQty ;;
  }

  measure: WorkOrderQty {
    type: sum
    sql: ${TABLE}.OrderQty ;;
  }
}
